version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mongo_network

volumes:
  mongo_data:
    driver: local
  mongo_config:
    driver: local

networks:
  mongo_network:
    driver: bridge

